- name: 创建 csi-cephfs values 目录
  file:
    name: /etc/kubernetes/plugins/csi-cephfs
    state: directory

- name: 复制 charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "ceph-csi-cephfs"

- name: 生成 ceph-csi-cephfs values.yml
  template:
    src: custom-values-ceph-csi-cephfs.yaml.j2
    dest: /etc/kubernetes/plugins/csi-cephfs/values.yaml
    owner: root
    mode: 0644

- name: Install ceph-csi-cephfs helm charts
  kubernetes.core.helm:
    atomic: no
    name: ceph-csi-cephfs
    chart_ref: "{{ helm_charts_dir }}/ceph-csi-cephfs"
    values_files:
      - /etc/kubernetes/plugins/csi-cephfs/values.yaml
    state: present
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"
  when:
    - ansible_distribution == "openEuler"

- name: Install ceph-csi-cephfs helm charts
  shell: helm upgrade -i ceph-csi-cephfs {{ helm_charts_dir }}/ceph-csi-cephfs -f /etc/kubernetes/plugins/csi-cephfs/values.yaml
  when:
    - ansible_distribution != "openEuler"
