- name: 创建 lvm-csi values 目录
  file:
    name: /etc/kubernetes/plugins/lvm-csi
    state: directory

- name: 复制 lvm-csi charts 目录
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "lvm-csi"

- name: 生成 lvm-csi values.yml
  template:
    src: custom-values-lvm-csi.yaml.j2
    dest: /etc/kubernetes/plugins/lvm-csi/values.yaml
    owner: root
    mode: 0644

- name: Install lvm-csi helm charts
  kubernetes.core.helm:
    atomic: no
    name: lvm-csi
    chart_ref: "{{ helm_charts_dir }}/lvm-csi"
    values_files:
      - /etc/kubernetes/plugins/lvm-csi/values.yaml
    state: present 
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"
  when:
    - ansible_distribution == "openEuler"