---
- name: create harbor values dir
  file:
    name: /etc/kubernetes/plugins/harbor
    state: directory

- name: copy harbor charts dir
  copy:
    src: "{{ item }}"
    dest: "{{ helm_charts_dir }}/"
  loop:
    - "harbor"

- name: create harbor values.yml
  template:
    src: custom-values-harbor.yaml.j2
    dest: /etc/kubernetes/plugins/harbor/harbor.yaml
    owner: root
    mode: 0644

- name: Install harbor helm charts
  kubernetes.core.helm:
    atomic: no
    name: harbor
    chart_ref: "{{ helm_charts_dir }}/harbor"
    values_files:
      - /etc/kubernetes/plugins/harbor/harbor.yaml
    state: present 
    wait: yes
    wait_timeout: "{{ helm_wait_timeout }}"
    release_namespace: "{{ helm_install_namespace }}"
  when:
    - ansible_distribution == "openEuler"

- name: Install harbor helm charts
  shell: helm upgrade -i harbor {{ helm_charts_dir }}/harbor -f /etc/kubernetes/plugins/harbor/harbor.yaml
  when:
    - ansible_distribution != "openEuler"
