---
- name: Docker Login
  docker_login:
    registry: "{{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002"
    username: "{{ harbor_local_username }}"
    debug: true
    password: "{{ harbor_local_password }}"
  when:
    - ansible_distribution == "openEuler"

- name: Find local chart
  command: "ls {{ helm_charts_dir }}/local_charts"
  register: dir_out
  when:
    - ansible_distribution == "openEuler"

- name: Add tag to harbor image
  community.docker.docker_image:
    name: "{{ kube_image_repository }}/{{ item }}:{{ harbor_local_chart_image_version }}"  
    repository: "{{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002/library/{{ item }}:arm" 
    force_tag: yes 
    push: true
    source: local
  with_items: "{{ dir_out.stdout_lines }}"
  when:
    - ansible_distribution == "openEuler"

- name: Docker Login
  vars:
    repo_username: "{{ harbor_local_username }}"
    repo_password: "{{ harbor_local_password }}"
    repo_url: "http://{{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002"
  shell: 'docker login "{{ repo_url }}" --username "{{ repo_username }}" --password "{{ repo_password }}" '
  when:
    - ansible_distribution != "openEuler"

- name: Add tag to harbor image
  shell: |
    docker tag {{ kube_image_repository }}/{{ item }}:{{ harbor_local_chart_image_version }} {{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002/library/{{ item }}:arm
    docker push {{ hostvars[groups['harbor'][0]]['ansible_' + hostvars[groups['harbor'][0]]['api_interface']]['ipv4']['address'] }}:30002/library/{{ item }}:arm
  with_items:
    - prmp-web-arm
    - prmp-arm
    - mysql
    - redis
    - kubernetes-entrypoint
  when:
    - ansible_distribution != "openEuler"
