---
- block:
  - name: KubeSphere | Getting sonarqube host
    shell: >
      kubectl get cm -n default kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "sonarQube:" -A 2 | grep "host" | awk '{print $2}'
    register: sonarqube_host

  - name: KubeSphere | Getting sonarqube token
    shell: >
      kubectl get cm -n default kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "sonarQube:" -A 2 | grep "token" | awk '{print $2}'
    register: sonarqube_token
  when:
    - devops.sonarqube is not defined

- set_fact:
    sonarQubeHost: "{{ sonarqube_host.stdout }}"
    sonarQubeToken: "{{ sonarqube_token.stdout }}"
  when:
    - sonarqube_host is defined and sonarqube_host.stdout is defined and sonarqube_host.stdout != ""
    - sonarqube_token is defined and sonarqube_token.stdout is defined and sonarqube_token.stdout != ""

- set_fact:
    sonarQubeHost: "{{ devops.sonarqube.externalSonarUrl }}"
    sonarQubeToken: "{{ devops.sonarqube.externalSonarToken }}"
  when:
    - devops.sonarqube is defined
    - devops.sonarqube.externalSonarUrl is defined
    - devops.sonarqube.externalSonarToken is defined

- block:
  - name: KubeSphere | Getting es index prefix
    shell: >
      kubectl get cm -n default kubesphere-config -o jsonpath='{.data.kubesphere\.yaml}' | grep "logging:" -A 2 | grep "indexPrefix" | awk '{print $2}'
    register: es_indexPrefix

- set_fact:
    esIndexPrefix: "{{ es_indexPrefix.stdout }}"
  when:
    - es_indexPrefix is defined and es_indexPrefix.stdout is defined and es_indexPrefix.stdout != ""

- name: KubeSphere | Getting token
  shell: >
    kubectl get secret kubesphere-secret -o jsonpath='{.data.token}' | base64 -d
  register: ks_token_str

- name: KubeSphere | Getting ks-secret
  shell: >
    kubectl get secret kubesphere-secret -o jsonpath='{.data.secret}' | base64 -d
  register: ks_secret_str

- name: KubeSphere | Getting Kubernetes master num
  shell: >
    kubectl get node | awk '{if(NR>1){print $3}}' | grep master | wc -l
  register: masters
  failed_when: false


- name: KubeSphere | Setting master num
  set_fact:
    enableHA: >-
      {% if masters is defined and masters.stdout is defined and masters.stdout != "0" and masters.stdout != "1" %}true{% else %}false{% endif %}
  when:
    - enableHA is not defined

- name: OpenPitrix | Check OpenPitrix v3.0.0
  shell: >
    kubectl get deploy openpitrix-hyperpitrix-deployment -n openpitrix-system 2>1 -oNAME | wc -l
  register: openpitrix_deploy_count

- set_fact:
    OPMigrate: true
  when:
    - openpitrix_deploy_count.stdout == "1"

- name: KubeSphere | Creating manifests
  template:
    src: "kubesphere-config.yaml.j2"
    dest: "/etc/kubernetes/plugins/ks-core/kubesphere-config.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"


- name: KubeSphere | Initing KubeSphere
  shell: "kubectl apply -f /etc/kubernetes/plugins/ks-core/kubesphere-config.yaml"
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- import_tasks: ks-restart.yaml
